apiVersion: v1
kind: Secret
metadata:
  name: shlink-secret
  namespace: apps
type: Opaque
stringData:
  database-password: 'your-database-password'
  geolite-license-key: 'your-geolite-license-key'
  shlink-server-api-key: 'your-shlink-server-api-key'
  