apiVersion: v1
kind: Secret
metadata:
  name: infisical-secret
  namespace: core-infra
type: Opaque
stringData:
  AUTH_SECRET: "your-auth-secret"
  ENCRYPTION_KEY: "your-encryption-key"
  SITE_URL: "your-site-url"
  DB_CONNECTION_URI: "your-db-connection-uri"
  SMTP_HOST: "your-smtp-host"
  SMTP_USERNAME: "your-smtp-username"
  SMTP_PASSWORD: "your-smtp-password"
  SMTP_PORT: "your-smtp-port"
  SMTP_FROM_ADDRESS: "your-smtp-from-address"
  SMTP_FROM_NAME: "your-smtp-from-name"