apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: vaultwarden-secret-sync
  namespace: apps
spec:
  hostAPI: https://infisical.junbeom.work/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "vaultwarden"
        envSlug: "prod"
        secretsPath: "/"
      credentialsRef:
        secretName: infisical-auth-token
        secretNamespace: core-infra
  managedKubeSecretReferences:
    - secretName: vaultwarden-secret
      secretNamespace: apps
      secretType: Opaque