apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secret
  namespace: apps
type: Opaque
stringData:
  admin-token: 'your-admin-token'
  database-url: 'your-database-url'
  smtp-password: 'your-smtp-password'
  smtp-user: 'your-smtp-user'