apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: crowdsec-secret-sync
  namespace: core-infra
spec:
  hostAPI: https://infisical.junbeom.work/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "crowdsec"
        envSlug: "prod"
        secretsPath: "/"
      credentialsRef:
        secretName: infisical-auth-token
        secretNamespace: core-infra
  managedKubeSecretReferences:
    - secretName: crowdsec-secret
      secretNamespace: core-infra
      secretType: Opaque