# ====================================================================
# Cloudbeaver Helm Chart Values
# https://artifacthub.io/packages/helm/avisto/cloudbeaver
# ====================================================================

image:
  registry: docker.io
  repository: dbeaver/cloudbeaver
  tag: "26"
  digest: ""
  
  pullPolicy: IfNotPresent

livenessProbe:
  enabled: true
  initialDelaySeconds: 60
  periodSeconds: 5
  timeoutSeconds: 1
  failureThreshold: 5

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 1
  failureThreshold: 5

hostname: "beaver.junbeom.work"

ingress:
  enabled: true
  ingressClassName: "traefik"
  pathType: Prefix
  hostname: "beaver.junbeom.work"
  path: "/"

  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: "apps-cloudflare-only@kubernetescrd"
  tls: true
 
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi
  storageClass: "longhorn"