# ====================================================================
# PostgreSQL Values
# https://artifacthub.io/packages/helm/bitnami/postgresql
# ====================================================================

image:
  registry: docker.io
  repository: bitnami/postgresql
  tags: "18.3.0-debian-12-r5"
  pullPolicy: IfNotPresent

auth:
  enablePostgresUser: true
  existingSecret: "postgres-secret"
  secretKeys:
    adminPasswordKey: postgres-password
  usePasswordFiles: true


primary:
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 10Gi
    storageClass: "local-path"