apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: n8n-secret-sync
  namespace: n8n
spec:
  hostAPI: https://infisical.techbara.dev/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "n8n"
        envSlug: "prod"
        secretsPath: "/"
      credentialsRef:
        secretName: infisical-auth-token
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: n8n-secret
      secretNamespace: n8n
      secretType: Opaque
