apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: shlink-secret-sync
  namespace: shlink
spec:
  hostAPI: https://infisical.techbara.dev/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "shlink"
        envSlug: "prod"
        secretsPath: "/"
      credentialsRef:
        secretName: infisical-auth-token
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: shlink-secret
      secretNamespace: shlink
      secretType: Opaque
