# ==================================================
# Secret: 데이터베이스 보안 정보
# ==================================================
apiVersion: v1
kind: Secret
metadata:
  name: ai-stack-secret
  namespace: apps
type: Opaque
stringData:
  open-webui-secret-key: "your_super_secure_secret_key_for_junbeom" # [수정 가능] 임의의 암호화 키