apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: homarr-secret-sync
  namespace: homarr
spec:
  hostAPI: https://infisical.techbara.dev/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "homarr"
        envSlug: "prod"
        secretsPath: "/"
      credentialsRef:
        secretName: infisical-auth-token
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: homarr-secret
      secretNamespace: homarr
      secretType: Opaque