# ==========================================
# Traefik v3 커스텀 설정 파일 (Helm Values)
# ==========================================

providers:
  kubernetesIngress:
    publishedService:
      enabled: false

ports:
  web:
    port: 8000
    expose:
      default: true
    exposedPort: 80
  websecure:
    port: 8443
    expose:
      default: true
    exposedPort: 443

deployment:
  kind: DaemonSet

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 0

ingressRoute:
  dashboard:
    enabled: false

hostNetwork: true
