apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: paperless-secret-sync
  namespace: paperless-ngx
spec:
  hostAPI: https://infisical.techbara.dev/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "paperless-ngx"
        envSlug: "prod"
        secretsPath: "/"
      credentialsRef:
        secretName: infisical-auth-token
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: paperless-secret
      secretNamespace: paperless-ngx
      secretType: Opaque
