# ==================================================
# Secret: 데이터베이스 보안 정보
# ==================================================
apiVersion: v1
kind: Secret
metadata:
  name: mealie-secret
  namespace: apps
type: Opaque
stringData:
  postgres-user: "your_postgres_user"
  postgres-password: "your_postgres_password"
  postgres-db: "your_postgres_db"
  postgres-port: "your_postgres_port"
  postgres-host: "your_postgres_host"
  smtp-password: "your_smtp_password"