apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: brevo-secret-sync
  namespace: infisical
spec:
  hostAPI: https://infisical.techbara.dev/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: "brevo"
        envSlug: "prod"
        secretsPath: "/"
      credentialsRef:
        secretName: infisical-auth-token
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: brevo-secret
      secretNamespace: karakeep
      secretType: Opaque
    - secretName: brevo-secret
      secretNamespace: vaultwarden
      secretType: Opaque
    - secretName: brevo-secret
      secretNamespace: yuvomi
      secretType: Opaque