# ================================================
# Longhorn Helm Chart Values
# ================================================

global:
  timezone: "Asia/Seoul"


persistence:
  defaultClassReplicaCount: 1
  reclaimPolicy: Retain 

csi:
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1

defaultSettings:
  defaultReplicaCount: "1"
  replicaReplenishmentWaitInterval: 0
  defaultDataPath: "/data/longhorn"
  storageReservedPercentageForDefaultDisk: 5

longhornUI:
  replicas: 1

ingress:
  enabled: true
  ingressClassName: "traefik" 
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: "core-infra-cloudflare-only@kubernetescrd"
  host: "longhorn.junbeom.work"
  path: /
  pathType: Prefix
  tls: true
  