# ====================================================================
# PostgreSQL Helm Chart Values
# https://artifacthub.io/packages/helm/bitnami/postgresql
# ====================================================================

architecture: standalone

fullnameOverride: "postgres"

image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: latest
  pullPolicy: IfNotPresent

auth:
  enablePostgresUser: true
  existingSecret: "postgres-secret"
  secretKeys:
    adminPasswordKey: POSTGRES_PASSWORD
  usePasswordFiles: true


primary:
  extraEnvVars:
    - name: TZ
      value: "Asia/Seoul"
  
  initdb:
    scripts:
      01_enable_pgvector.sql: |
        CREATE EXTENSION IF NOT EXISTS pgvector;

  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 15Gi
    storageClass: "longhorn"

  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1

  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1

  startupProbe:
    enabled: false
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 15
    successThreshold: 1

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 2000m
      memory: 1.5Gi