apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-cli
  namespace: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-cli
  template:
    metadata:
      labels:
        app: minio-cli
    spec:
      containers:
      - name: mc
        image: docker.io/bitnamilegacy/minio-client:latest
        command: ["/bin/bash", "-c"]
        args:
          - |
            mc alias set myminio http://minio.minio.svc.cluster.local:9000 "$ROOT_USER" "$ROOT_PASSWORD";
            sleep infinity
        env:
        - name: ROOT_USER
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: ROOT_USER
        - name: ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: ROOT_PASSWORD