---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-php-config
  namespace: apps
data:
  custom-php.ini: |
    memory_limit = 512M
    upload_max_filesize = 64M
    post_max_size = 64M
    max_execution_time = 300
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-app
  namespace: apps
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: wordpress-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-app
  namespace: apps
  annotations:
    diun.enable: "true"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wordpress-app
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      containers:
        - name: wordpress
          image: wordpress:6-php8.5-apache
          imagePullPolicy: IfNotPresent
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: mariadb-host
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: mariadb-user
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: mariadb-password
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: mariadb-database
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
            - name: php-config
              mountPath: /usr/local/etc/php/conf.d/custom-php.ini
              subPath: custom-php.ini
            - name: wp-local-uploads
              mountPath: /var/www/html/wp-content/uploads
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wordpress-pvc
        - name: php-config
          configMap:
            name: wp-php-config
        - name: wp-local-uploads
          hostPath:
            path: /var/local/k3s-hostpath/wordpress-uploads
            type: DirectoryOrCreate

---
# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-cloudflare"
    traefik.ingress.kubernetes.io/router.middlewares: "core-infra-cloudflare-only@kubernetescrd"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  rules:
    - host: www.junbeom.work
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-app
                port:
                  number: 80
  tls:
    - hosts:
        - www.junbeom.work
      secretName: wordpress-tls
      