apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
  namespace: apps
type: Opaque
stringData:
  mariadb-host: 'your-mariadb-host'
  mariadb-user: 'your-mariadb-user'
  mariadb-password: 'your-mariadb-password'
  mariadb-database: 'your-mariadb-database'